/**
 * Const objects derived from orderStatusEnum and orderItemStatusEnum in schema.ts.
 * Use these throughout order/item processing to avoid hardcoded string literals.
 */

export const ORDER_STATUS = {
  PENDIENTE: "PENDIENTE",
  APROBACION: "APROBACION",
  PROGRAMACION: "PROGRAMACION",
  PRODUCCION: "PRODUCCION",
  ATRASADO: "ATRASADO",
  FINALIZADO: "FINALIZADO",
  ENTREGADO: "ENTREGADO",
  CANCELADO: "CANCELADO",
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const ORDER_STATUS_VALUES = Object.values(ORDER_STATUS);

export const ORDER_ITEM_STATUS = {
  PENDIENTE: "PENDIENTE",
  APROBACION: "APROBACION",
  APROBACION_ACTUALIZACION: "PENDIENTE_PRODUCCION_ACTUALIZACION",
  APROBADO_CAMBIO: "APROBADO_CAMBIO",
  RECHAZADO_CAMBIO: "RECHAZADO_CAMBIO",
  PENDIENTE_PRODUCCION: "PENDIENTE_PRODUCCION",
  PENDIENTE_PRODUCCION_ACTUALIZACION: "PENDIENTE_PRODUCCION_ACTUALIZACION",
  MONTAJE: "MONTAJE",
  IMPRESION: "IMPRESION",
  SUBLIMACION: "SUBLIMACION",
  CORTE_MANUAL: "CORTE_MANUAL",
  CORTE_LASER: "CORTE_LASER",
  PENDIENTE_CONFECCION: "PENDIENTE_CONFECCION",
  CONFECCION: "CONFECCION",
  EN_BODEGA: "EN_BODEGA",
  EMPAQUE: "EMPAQUE",
  ENVIADO: "ENVIADO",
  COMPLETADO: "COMPLETADO",
  CANCELADO: "CANCELADO",
} as const;

export type OrderItemStatus =
  (typeof ORDER_ITEM_STATUS)[keyof typeof ORDER_ITEM_STATUS];

export const ORDER_ITEM_STATUS_VALUES = Object.values(ORDER_ITEM_STATUS);
