import { ORDER_ITEM_STATUS } from "@/src/utils/order-status";

const CONSOLIDATED_OPERARIO_ROLE = "OPERARIO";
const LEGACY_OPERARIO_ROLES = new Set([
  "OPERARIO_FLOTER",
  "OPERARIO_SUBLIMACION",
  "OPERARIO_CORTE_MANUAL",
  "OPERARIO_CORTE_LASER",
  "OPERARIO_MONTAJE",
]);

const STATUS_ROLE_MAP: Record<string, string[]> = {
  PENDIENTE: [
    "ADMINISTRADOR",
    "ASESOR",
    "LIDER_SUMINISTROS",
    "COMPRA_NACIONAL",
    "COMPRA_INTERNACIONAL",
  ],
  APROBACION: [
    "ADMINISTRADOR",
    "ASESOR",
    "LIDER_SUMINISTROS",
    "COMPRA_NACIONAL",
    "COMPRA_INTERNACIONAL",
  ],
  PENDIENTE_PRODUCCION: [
    "ADMINISTRADOR",
    "ASESOR",
    "LIDER_SUMINISTROS",
    "COMPRA_NACIONAL",
    "COMPRA_INTERNACIONAL",
    "OPERARIO_BODEGA",
  ],
  MONTAJE: [CONSOLIDATED_OPERARIO_ROLE, "ADMINISTRADOR"],
  IMPRESION: [CONSOLIDATED_OPERARIO_ROLE, "ADMINISTRADOR"],
  SUBLIMACION: [CONSOLIDATED_OPERARIO_ROLE, "ADMINISTRADOR"],
  CORTE_MANUAL: [CONSOLIDATED_OPERARIO_ROLE, "ADMINISTRADOR"],
  CORTE_LASER: [CONSOLIDATED_OPERARIO_ROLE, "ADMINISTRADOR"],
  PENDIENTE_CONFECCION: ["ADMINISTRADOR", "OPERARIO_INTEGRACION_CALIDAD"],
  CONFECCION: ["ADMINISTRADOR", "OPERARIO_INTEGRACION_CALIDAD", "EMPAQUE"],
  EN_BODEGA: ["ADMINISTRADOR", "EMPAQUE", "OPERARIO_BODEGA"],
  EMPAQUE: ["ADMINISTRADOR", "EMPAQUE"],
  ENVIADO: ["ADMINISTRADOR", "EMPAQUE"],
  COMPLETADO: ["ADMINISTRADOR", "EMPAQUE"],
  CANCELADO: ["ADMINISTRADOR"],
};

const EXTRA_STATUSES = [
  ORDER_ITEM_STATUS.APROBACION_ACTUALIZACION,
  ORDER_ITEM_STATUS.PENDIENTE_PRODUCCION_ACTUALIZACION,
  ORDER_ITEM_STATUS.APROBADO_CAMBIO,
  ORDER_ITEM_STATUS.RECHAZADO_CAMBIO,
] as const;

const ALL_STATUSES = [
  ...Object.keys(STATUS_ROLE_MAP),
  ...EXTRA_STATUSES,
] as const;

const ALL_STATUS_SET = new Set(ALL_STATUSES);

const leaderAllowed = ALL_STATUSES.filter(
  (status) => status !== ORDER_ITEM_STATUS.CANCELADO,
);

const STATUS_TRANSITIONS: Record<string, string[]> = {
  PENDIENTE: [ORDER_ITEM_STATUS.APROBACION],
  APROBACION: [ORDER_ITEM_STATUS.PENDIENTE_PRODUCCION],
  APROBACION_ACTUALIZACION: [
    ORDER_ITEM_STATUS.PENDIENTE_PRODUCCION_ACTUALIZACION,
    ORDER_ITEM_STATUS.RECHAZADO_CAMBIO,
  ],
  PENDIENTE_PRODUCCION: [
    ORDER_ITEM_STATUS.MONTAJE,
    ORDER_ITEM_STATUS.IMPRESION,
    ORDER_ITEM_STATUS.SUBLIMACION,
    ORDER_ITEM_STATUS.CORTE_MANUAL,
    ORDER_ITEM_STATUS.CORTE_LASER,
    ORDER_ITEM_STATUS.PENDIENTE_CONFECCION,
  ],
  PENDIENTE_PRODUCCION_ACTUALIZACION: [
    ORDER_ITEM_STATUS.PENDIENTE_PRODUCCION,
    ORDER_ITEM_STATUS.APROBACION_ACTUALIZACION,
    ORDER_ITEM_STATUS.MONTAJE,
    ORDER_ITEM_STATUS.IMPRESION,
    ORDER_ITEM_STATUS.SUBLIMACION,
    ORDER_ITEM_STATUS.CORTE_MANUAL,
    ORDER_ITEM_STATUS.CORTE_LASER,
    ORDER_ITEM_STATUS.PENDIENTE_CONFECCION,
  ],
  MONTAJE: [ORDER_ITEM_STATUS.PENDIENTE_CONFECCION],
  IMPRESION: [ORDER_ITEM_STATUS.PENDIENTE_CONFECCION],
  SUBLIMACION: [ORDER_ITEM_STATUS.PENDIENTE_CONFECCION],
  CORTE_MANUAL: [ORDER_ITEM_STATUS.PENDIENTE_CONFECCION],
  CORTE_LASER: [ORDER_ITEM_STATUS.PENDIENTE_CONFECCION],
  PENDIENTE_CONFECCION: [ORDER_ITEM_STATUS.CONFECCION],
  CONFECCION: [ORDER_ITEM_STATUS.EN_BODEGA],
  EN_BODEGA: [ORDER_ITEM_STATUS.EMPAQUE],
  EMPAQUE: [ORDER_ITEM_STATUS.ENVIADO],
  ENVIADO: [ORDER_ITEM_STATUS.COMPLETADO],
  APROBADO_CAMBIO: [ORDER_ITEM_STATUS.PENDIENTE_PRODUCCION_ACTUALIZACION],
  RECHAZADO_CAMBIO: [ORDER_ITEM_STATUS.APROBACION_ACTUALIZACION],
  COMPLETADO: [],
  CANCELADO: [],
};

export function getAllowedStatusesForRole(role: string | null) {
  if (!role) return [] as string[];
  if (role === "ADMINISTRADOR") return ALL_STATUSES.slice();
  if (role === "LIDER_OPERACIONAL") return leaderAllowed.slice();

  const normalizedRole = LEGACY_OPERARIO_ROLES.has(role)
    ? CONSOLIDATED_OPERARIO_ROLE
    : role;

  return Object.entries(STATUS_ROLE_MAP)
    .filter(([, roles]) => roles.includes(normalizedRole))
    .map(([status]) => status);
}

export function getAllowedNextStatuses(
  role: string | null,
  current: string | null,
) {
  if (!role || !current) return [] as string[];
  if (!ALL_STATUS_SET.has(current)) return [] as string[];

  if (role === "ADMINISTRADOR") {
    return ALL_STATUSES.slice();
  }

  const allowedByRole = new Set(getAllowedStatusesForRole(role));
  const next = STATUS_TRANSITIONS[current] ?? [];

  return next.filter((status) => allowedByRole.has(status));
}

export function canRoleChangeStatus(
  role: string | null,
  current: string | null,
  next: string,
) {
  if (!role) return false;
  if (!ALL_STATUS_SET.has(next)) return false;

  if (role === "ADMINISTRADOR") return true;

  if (!current || !ALL_STATUS_SET.has(current)) return false;

  const allowed = getAllowedStatusesForRole(role);

  if (!allowed.includes(next)) return false;

  const allowedNext = STATUS_TRANSITIONS[current] ?? [];

  return allowedNext.includes(next) || next === current;
}

export function isOperarioRole(role: string | null) {
  if (!role) return false;

  return (
    role === CONSOLIDATED_OPERARIO_ROLE ||
    role.startsWith("OPERARIO_") ||
    role === "EMPAQUE" ||
    role === "CONFECCIONISTA"
  );
}
