export type EmployeeFormPrefill = Partial<{
  userId: string;
  name: string;
  identificationType: string;
  identification: string;
  dv: string;
  email: string;
  intlDialCode: string;
  mobile: string;
  landline: string;
  extension: string;
  address: string;
  city: string;
  department: string;
  employeeImageUrl: string;
  signatureImageUrl: string;
  roleId: string;
  isActive: boolean;
  createUserEmail: string;
}>;
