import type { PedidoGroup } from "./mes-types";

import { generateTicket } from "./mes-utils";

export const MOCK_DATA: PedidoGroup[] = [
  {
    pedido: "VN-013875",
    cliente: "BARCA ACADEMIA",
    fechaPedido: "30/01/2026",
    fechaEntrega: "06/02/2026",
    vendedor: "NATALIA",
    plazo: 7,
    estado: "SIN TRAMITAR",
    expanded: true,
    disenos: [
      {
        diseno: 1,
        detalle: "CORTAVIENTOS",
        tela: "NOVAK",
        genero: "MASCULINO",
        ticketMontaje: generateTicket("montaje", 0),
        ticketPlotter: generateTicket("plotter", 0),
        tallas: [{ talla: "T/6", cantidad: 1, estado: "pendiente" }],
      },
    ],
  },
  {
    pedido: "VN-013818",
    cliente: "CLUB DEPORTIVO BRASILIA",
    fechaPedido: "22/01/2026",
    fechaEntrega: "14/02/2026",
    vendedor: "MAURICIO",
    plazo: 23,
    estado: "EN PROCESO",
    expanded: true,
    disenos: [
      {
        diseno: 1,
        detalle: "CORTAVIENTOS",
        tela: "NOVAK",
        genero: "MASCULINO",
        ticketMontaje: generateTicket("montaje", 1),
        ticketPlotter: generateTicket("plotter", 1),
        tallas: [
          {
            talla: "T/6",
            cantidad: 6,
            estado: "completado",
            responsable: "Laura M.",
            fechaInicio: "23/01",
            fechaFin: "24/01",
          },
          {
            talla: "T/8",
            cantidad: 22,
            estado: "completado",
            responsable: "Laura M.",
            fechaInicio: "23/01",
            fechaFin: "24/01",
          },
          {
            talla: "T/10",
            cantidad: 22,
            estado: "en_proceso",
            responsable: "Carlos R.",
            fechaInicio: "25/01",
          },
          {
            talla: "T/12",
            cantidad: 30,
            estado: "en_proceso",
            responsable: "Carlos R.",
            fechaInicio: "25/01",
          },
          { talla: "T/14", cantidad: 30, estado: "pendiente" },
          { talla: "T/16", cantidad: 30, estado: "pendiente" },
          { talla: "T/S", cantidad: 30, estado: "pendiente" },
          { talla: "T/M", cantidad: 30, estado: "pendiente" },
          { talla: "T/L", cantidad: 25, estado: "pendiente" },
          { talla: "T/XL", cantidad: 20, estado: "pendiente" },
          {
            talla: "T/2XL",
            cantidad: 5,
            estado: "reponer",
            observacion: "Arruga en papel",
          },
        ],
      },
      {
        diseno: 2,
        detalle: "SUDADERA BOLSILLO LATERAL",
        tela: "NOVAK",
        genero: "MASCULINO",
        ticketMontaje: generateTicket("montaje", 2),
        ticketPlotter: generateTicket("plotter", 2),
        tallas: [
          {
            talla: "T/6",
            cantidad: 6,
            estado: "en_proceso",
            responsable: "Ana G.",
            fechaInicio: "26/01",
          },
          { talla: "T/8", cantidad: 22, estado: "pendiente" },
          { talla: "T/10", cantidad: 22, estado: "pendiente" },
          { talla: "T/12", cantidad: 30, estado: "pendiente" },
          { talla: "T/14", cantidad: 30, estado: "pendiente" },
          { talla: "T/16", cantidad: 30, estado: "pendiente" },
        ],
      },
    ],
  },
  {
    pedido: "VN-013795",
    cliente: "ACADEMIA FUTBOL ELITE",
    fechaPedido: "18/01/2026",
    fechaEntrega: "10/02/2026",
    vendedor: "CARLOS",
    plazo: 15,
    estado: "TARDE",
    expanded: false,
    disenos: [
      {
        diseno: 1,
        detalle: "CAMISETA MANGA CORTA",
        tela: "PERFORMANCE DRY",
        genero: "MIXTO",
        ticketMontaje: generateTicket("montaje", 3),
        ticketPlotter: generateTicket("plotter", 3),
        tallas: [
          {
            talla: "T/S",
            cantidad: 10,
            estado: "completado",
            responsable: "Luis P.",
          },
          {
            talla: "T/M",
            cantidad: 25,
            estado: "completado",
            responsable: "Luis P.",
          },
          {
            talla: "T/L",
            cantidad: 20,
            estado: "reponer",
            observacion: "Falla sublimacion",
          },
          { talla: "T/XL", cantidad: 8, estado: "pendiente" },
        ],
      },
    ],
  },
  {
    pedido: "VN-014002",
    cliente: "COLEGIO SAN MARCOS",
    fechaPedido: "02/02/2026",
    fechaEntrega: "18/02/2026",
    vendedor: "LAURA",
    plazo: 16,
    estado: "COMPLETADO",
    expanded: false,
    disenos: [
      {
        diseno: 1,
        detalle: "CAMISETA ARQUERO",
        tela: "DRY TECH",
        genero: "MIXTO",
        ticketMontaje: generateTicket("montaje", 4),
        ticketPlotter: generateTicket("plotter", 4),
        tallas: [
          {
            talla: "T/S",
            cantidad: 12,
            estado: "completado",
            responsable: "Equipo A",
            fechaInicio: "03/02",
            fechaFin: "06/02",
          },
          {
            talla: "T/M",
            cantidad: 18,
            estado: "completado",
            responsable: "Equipo A",
            fechaInicio: "03/02",
            fechaFin: "06/02",
          },
          {
            talla: "T/L",
            cantidad: 18,
            estado: "completado",
            responsable: "Equipo B",
            fechaInicio: "05/02",
            fechaFin: "08/02",
          },
        ],
      },
    ],
  },
  {
    pedido: "VN-014015",
    cliente: "LIGA JUVENIL METRO",
    fechaPedido: "04/02/2026",
    fechaEntrega: "20/02/2026",
    vendedor: "SERGIO",
    plazo: 16,
    estado: "EN PROCESO",
    expanded: false,
    disenos: [
      {
        diseno: 1,
        detalle: "SUDADERA ENTRENAMIENTO",
        tela: "MICROFIBRA PREMIUM",
        genero: "MASCULINO",
        ticketMontaje: generateTicket("montaje", 5),
        ticketPlotter: generateTicket("plotter", 5),
        tallas: [
          {
            talla: "T/M",
            cantidad: 14,
            estado: "completado",
            responsable: "Paula V.",
            fechaInicio: "05/02",
            fechaFin: "07/02",
          },
          {
            talla: "T/L",
            cantidad: 22,
            estado: "en_proceso",
            responsable: "Paula V.",
            fechaInicio: "08/02",
          },
          {
            talla: "T/XL",
            cantidad: 10,
            estado: "reponer",
            observacion: "Faltante de cuello sublimado",
          },
          { talla: "T/2XL", cantidad: 6, estado: "pendiente" },
        ],
      },
    ],
  },
];
