"use client";

import { useEffect, useState } from "react";
import { Button } from "@heroui/button";
import { Card, CardBody } from "@heroui/card";
import { Chip } from "@heroui/chip";

type Certificate220Item = {
  id: string;
  vigenciaFiscal: number;
  totalIngresos: string;
  totalRetenciones: string;
  status: string;
  pdfUrl: string | null;
};

type Certificate220Response = {
  items: Certificate220Item[];
};

export function Certificate220Panel() {
  const [loading, setLoading] = useState(false);
  const [items, setItems] = useState<Certificate220Item[]>([]);

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const response = await fetch("/api/hcm/certificados220?page=1&pageSize=10");

        if (!response.ok) throw new Error("Unable to load certificate records.");

        const json = (await response.json()) as Certificate220Response;

        setItems(json.items ?? []);
      } finally {
        setLoading(false);
      }
    }

    void load();
  }, []);

  return (
    <Card className="border border-default-200/50">
      <CardBody className="space-y-4 p-5">
        <div>
          <h3 className="text-lg font-semibold">Certificate 220</h3>
          <p className="text-sm text-default-500">Annual income and withholding statements generated by payroll.</p>
        </div>
        <div className="space-y-2">
          {items.map((item) => (
            <div key={item.id} className="flex items-center justify-between rounded-medium border border-default-200/60 p-3">
              <div>
                <p className="text-sm font-medium">Fiscal year {item.vigenciaFiscal}</p>
                <p className="text-xs text-default-500">Income: {item.totalIngresos} · Withholdings: {item.totalRetenciones}</p>
              </div>
              <div className="flex items-center gap-2">
                <Chip size="sm" variant="flat">{item.status}</Chip>
                {item.pdfUrl ? (
                  <Button as="a" href={item.pdfUrl} size="sm" target="_blank" variant="flat">PDF</Button>
                ) : null}
              </div>
            </div>
          ))}
          {!loading && items.length === 0 ? (
            <p className="text-sm text-default-500">No 220 certificates available yet.</p>
          ) : null}
        </div>
      </CardBody>
    </Card>
  );
}
