import type { moldingTemplates } from "../schema";

type MoldingTemplateSeed = Omit<
  typeof moldingTemplates.$inferInsert,
  "id" | "createdBy" | "createdAt" | "updatedAt"
>;

export const moldingTemplatesSeed: MoldingTemplateSeed[] = [
  {
    moldingCode: "D.N-CLL-001",
    version: 1,
    garmentType: "CAMISILLA",
    garmentSubtype: null,
    designDetail:
      "CAMISILLA - TIPO VOLLEY / TIPO PETO / TIPO BALONCESTO / PROMESAS / TIPO DOBLE FAS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: "CUELLO REDONDO SESGADO 3,5 cm / CUELLO EN V 4,5 cm",
    sesgoType: "SOBREPUESTO 4,5 cm / NORMAL 3,5 cm",
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Cuando la prenda se maneje sesgo sobrepuesto medidas 4,5 va en la misma tela, y sesgo normal de 3,5 siempre va en spring; tener en cuenta el color.",
    isActive: true,
  },
  {
    moldingCode: "D.N-CLL-002",
    version: 1,
    garmentType: "CAMISILLA",
    garmentSubtype: null,
    designDetail: "CAMISILLA - TIPO ESQUELETO / TIPO ATLETISMO / TIPO FIT",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: "CUELLO REDONDO SESGADO 3,5 cm",
    sesgoType: "SOBREPUESTO 4,5 cm / NORMAL 3,5 cm",
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Cuando la prenda se maneje sesgo sobrepuesto medidas 4,5 va en la misma tela, y sesgo normal de 3,5 siempre va en spring; tener en cuenta el color.",
    isActive: true,
  },
  {
    moldingCode: "D.N-CLL-003",
    version: 1,
    garmentType: "CAMISILLA",
    garmentSubtype: null,
    designDetail: "CAMISILLA CON CORTE LATERAL",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: "CUELLO NORMAL 4,5 cm / CUELLO ESPECIAL 6,0 cm",
    sesgoType: "SOBREPUESTO 4,5 cm / ESPECIAL 6,0 cm",
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: true,
    lateralMeshColor: null,
    observations:
      "Cuando la prenda se maneje sesgo sobrepuesto medidas 4,5 va en la misma tela, y sesgo normal de 3,5 siempre va en spring; tener en cuenta el color.",
    isActive: true,
  },
  {
    moldingCode: "D.N-LCR-004",
    version: 1,
    garmentType: "LICRA CORTA",
    garmentSubtype: null,
    designDetail: "LICRA CORTA",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-CTA-005",
    version: 1,
    garmentType: "CAMISETA",
    garmentSubtype: null,
    designDetail: "CAMISETA RUGBY / VOLLEY",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-CTA/CAP-006",
    version: 1,
    garmentType: "CAMISETA",
    garmentSubtype: "CON CAPUCHA",
    designDetail: "CAMISETA MANGA LARGA CON CAPUCHA",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: "FIJA",
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-PTA-007",
    version: 1,
    garmentType: "PANTALONETA",
    garmentSubtype: null,
    designDetail:
      "PANTALONETA FUTBOL - TIPO VOLLEY / TIPO PETO / TIPO BALONCESTO / PROMESAS / TIPO DOBLE FAS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-PTA4-008",
    version: 1,
    garmentType: "PANTALONETA",
    garmentSubtype: "4 TAPAS",
    designDetail:
      "PANTALONETA 4 TAPAS - TIPO VOLLEY / TIPO PETO / TIPO BALONCESTO / PROMESAS / TIPO DOBLE FAS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-PTA4-009",
    version: 1,
    garmentType: "PANTALONETA",
    garmentSubtype: "FRANJA LATERAL",
    designDetail: "PANTALONETA FRANJA LATERAL",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-PTA-007",
    version: 2,
    garmentType: "SHORT",
    garmentSubtype: "RUNNING 4 TAPAS",
    designDetail:
      "SHORT RUNNING 4 TAPAS - TIPO VOLLEY / TIPO PETO / TIPO BALONCESTO / PROMESAS / TIPO DOBLE FAS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-PL-0011",
    version: 1,
    garmentType: "POLO",
    garmentSubtype: null,
    designDetail:
      "POLO - TIPOS: CON CIERRE EN PERILLA / 2 BOTONES / 3 BOTONES / CON BROCHE / CON BOLSILLO (ARBITRO)",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    collarType: "CUELLO POLO",
    perillaColor: null,
    buttonType: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-BMD-012",
    version: 1,
    garmentType: "BERMUDA",
    garmentSubtype: null,
    designDetail:
      "BERMUDA - TIPO VOLLEY / TIPO PETO / TIPO BALONCESTO / PROMESAS / TIPO DOBLE FAS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-BMD-013",
    version: 1,
    garmentType: "BERMUDA",
    garmentSubtype: "BOXEO",
    designDetail: "BERMUDA DE BOXEO",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-SUD-014",
    version: 1,
    garmentType: "SUDADERA",
    garmentSubtype: null,
    designDetail:
      "SUDADERA CON CIERRE EN BOTA / CON CIERRE EN BOTA Y LATERAL / CON CIERRE EN BOTA Y FRANJA / CON CIERRE EN BOTA Y VENA",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    cuffType: "EN BOTA",
    zipperLocation: "BOTA / LATERAL",
    zipperColor: null,
    cordColor: null,
    hasElastic: true,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Cordon redondo Viomar: especificar color (BLANCO, NEGRO, AZUL OSCURO). Cierre lateral cuando aplique: BLANCO, NEGRO, AZUL REY, AZUL OSCURO, VERDE ANTIOQUIA, ROJO, VERDE OSCURO, AZUL NOCHE, AMARILLO. Elastico al final.",
    isActive: true,
  },
  {
    moldingCode: "D.N-SUD-015",
    version: 1,
    garmentType: "SUDADERA",
    garmentSubtype: null,
    designDetail:
      "SUDADERA DOS BOLSILLOS SENCILLA / CON CIERRE LATERAL / CON SESGO LATERAL / CON SESGO LATERAL Y CIERRE / RECTA CON CIERRE LATERALES / RECTA CON CIERRE LATERALES Y VENA",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    cuffType: null,
    zipperLocation: "LATERAL",
    zipperColor: null,
    cordColor: null,
    hasElastic: true,
    hiladillaColor: null,
    hasPocket: true,
    pocketZipperColor: null,
    sesgoType: "LATERAL",
    sesgoColor: null,
    neckType: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Cordon redondo Viomar: especificar color. Cierre lateral colores disponibles. Elastico.",
    isActive: true,
  },
  {
    moldingCode: "D.N-SUD-016",
    version: 1,
    garmentType: "SUDADERA",
    garmentSubtype: "BOTA RECTA CON PUNO",
    designDetail:
      "SUDADERA BOTA RECTA CON PUNO EN BOTA / JOGGER CON PUNO EN BOTA",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    cuffType: "PUNO EN BOTA",
    zipperLocation: null,
    zipperColor: null,
    cordColor: null,
    hasElastic: true,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: "Elastico. Cordon redondo Viomar cuando aplique.",
    isActive: true,
  },
  {
    moldingCode: "D.N-SUD/LAT-017",
    version: 1,
    garmentType: "SUDADERA",
    garmentSubtype: "CON LATERAL",
    designDetail:
      "SUDADERA BOTA RECTA CON PUNO EN BOTA (VARIANTE LATERAL) / JOGGER CON PUNO EN BOTA",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    cuffType: "PUNO EN BOTA",
    zipperLocation: "LATERAL",
    zipperColor: null,
    cordColor: null,
    hasElastic: true,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Cordon redondo Viomar (BLANCO, NEGRO, AZUL OSCURO). Cierre lateral colores disponibles. Elastico.",
    isActive: true,
  },
  {
    moldingCode: "D.N-SUD/LAT-018",
    version: 1,
    garmentType: "SUDADERA",
    garmentSubtype: "CON PROTECCION",
    designDetail:
      "SUDADERA BOTA RECTA CON PUNO EN BOTA CON PROTECCION / JOGGER CON PUNO EN BOTA CON PROTECCION",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    cuffType: "PUNO EN BOTA",
    zipperLocation: null,
    zipperColor: null,
    cordColor: null,
    hasElastic: true,
    hasProtection: true,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: "Incluye proteccion. Elastico.",
    isActive: true,
  },
  {
    moldingCode: "D.N-TOP-019",
    version: 1,
    garmentType: "TOP",
    garmentSubtype: null,
    designDetail: "TOP - SENCILLA / CON FAJON",
    fabric: null,
    color: null,
    gender: "FEMENINO",
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hasFajon: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-TOPFJ-020",
    version: 1,
    garmentType: "TOP",
    garmentSubtype: "CON FAJON",
    designDetail: "TOP CON FAJON - SENCILLA / CON FAJON",
    fabric: null,
    color: null,
    gender: "FEMENINO",
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hasFajon: true,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-CHT/F-021",
    version: 1,
    garmentType: "CHAQUETA",
    garmentSubtype: "CON CAPUCHA FIJA",
    designDetail:
      "CHAQUETA CON CAPUCHA FIJA - TIPO 1: CIERRE FRONTAL SENCILLA / TIPO 2: CIERRE FRONTAL CON PUNO Y FAJON",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: "FIJA",
    cuffType: null,
    hasFajon: false,
    liningType: null,
    liningColor: null,
    hasInnerLining: true,
    zipperLocation: "FRONTAL",
    zipperColor: null,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Especificar: tipo de manga, cuando el puno es sobrepuesto se maneja en la misma tela o en rib. Insumos: HILADILLA (colores basicos), FORROS, CIERRES.",
    isActive: true,
  },
  {
    moldingCode: "D.N-CHT/G-017",
    version: 1,
    garmentType: "CHAQUETA",
    garmentSubtype: "CON CAPUCHA GUARDABLE",
    designDetail:
      "CHAQUETA CON CAPUCHA GUARDABLE - TIPO 1: CIERRE FRONTAL SENCILLA / TIPO 2: CIERRE FRONTAL CON PUNO Y FAJON",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: "GUARDABLE",
    cuffType: null,
    hasFajon: false,
    liningType: null,
    liningColor: null,
    hasInnerLining: true,
    zipperLocation: "FRONTAL",
    zipperColor: null,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Especificar: tipo de manga y material del puno (misma tela o rib). Insumos: HILADILLA, FORROS, CIERRES.",
    isActive: true,
  },
  {
    moldingCode: "D.N-CHT/C-018",
    version: 1,
    garmentType: "CHAQUETA",
    garmentSubtype: "ENGUATADA TIPO MICHEL",
    designDetail:
      "CHAQUETA ENGUATADA TIPO MICHEL - TIPO 1: CIERRE FRONTAL SENCILLA / TIPO 2: CIERRE FRONTAL CON PUNO Y FAJON",
    fabric: "IMPERMEABLE O ANTIFLUIDOS",
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: true,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: null,
    cuffType: null,
    hasFajon: false,
    hasPocket: true,
    pocketZipperColor: null,
    liningType: "TERMICO FLECCE / MALLA / PERCHADO",
    liningColor: null,
    hasInnerLining: true,
    zipperLocation: "FRONTAL - HASTA EL CUELLO TIPO TORTUGA",
    zipperColor: null,
    hiladillaColor: null,
    neckType: "TORTUGA",
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations:
      "Material: Impermeable o antifluidos. Forro: Termico flecce / malla / perchado. Personalizacion: Bordado en bolsillo y/o espalda. Tela: Nautica, Vendaval Crushe, Universal, Orion o segun requerimiento. Opcionales: Mangas extraibles, Reflectivos, Bolsillos adicionales, Bordados, Estampados, Capota, Punos resortados o rectos. Insumos: Cremallera Nylon #6, Hilo 100% poliester.",
    isActive: true,
  },
  {
    moldingCode: "D.N-COT/C-019",
    version: 1,
    garmentType: "CORTAVIENTO",
    garmentSubtype: "SOLO CUELLO",
    designDetail:
      "CORTAVIENTO SOLO CUELLO - TIPO 1: CIERRE FRONTAL SENCILLA / TIPO 2: CIERRE FRONTAL CON PUNO Y FAJON",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: null,
    cuffType: null,
    hasFajon: false,
    liningType: null,
    zipperLocation: "FRONTAL",
    zipperColor: null,
    hiladillaColor: null,
    neckType: "CUELLO SOLO (SIN CAPUCHA)",
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: "Especificar tipo de manga y material del puno.",
    isActive: true,
  },
  {
    moldingCode: "D.N-COT/G-020",
    version: 1,
    garmentType: "CORTAVIENTO",
    garmentSubtype: "CON CAPUCHA GUARDABLE",
    designDetail:
      "CORTAVIENTO CON CAPUCHA GUARDABLE - TIPO 1: CIERRE FRONTAL SENCILLA / TIPO 2: CIERRE FRONTAL CON PUNO Y FAJON",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: "GUARDABLE",
    cuffType: null,
    hasFajon: false,
    liningType: null,
    zipperLocation: "FRONTAL",
    zipperColor: null,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: "Especificar tipo de manga y material del puno.",
    isActive: true,
  },
  {
    moldingCode: "D.N-COT/F-021",
    version: 1,
    garmentType: "CORTAVIENTO",
    garmentSubtype: "CON CAPUCHA FIJA",
    designDetail:
      "CORTAVIENTO CON CAPUCHA FIJA - TIPO 1: CIERRE FRONTAL SENCILLA / TIPO 2: CIERRE FRONTAL CON PUNO Y FAJON",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: "FIJA",
    cuffType: null,
    hasFajon: false,
    liningType: null,
    zipperLocation: "FRONTAL",
    zipperColor: null,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: "Especificar tipo de manga y material del puno.",
    isActive: true,
  },
  {
    moldingCode: "D.N-CHP-C-022",
    version: 1,
    garmentType: "BUSO",
    garmentSubtype: null,
    designDetail:
      "BUSO - SENCILLO / HODDIE / HODDIE (CHOMPA) CON CAPUCHA / RUNNING / CON CIERRE / TIPO BOLSILLO CANGURO PARTIDO Y COMPLETO",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hoodType: null,
    hasPocket: false,
    zipperLocation: null,
    zipperColor: null,
    hiladillaColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-BEIS/S-023",
    version: 1,
    garmentType: "BEISBOLERA",
    garmentSubtype: null,
    designDetail: "BEISBOLERA - FULL BOTONES / DOS BOTONES",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: true,
    snap: false,
    tag: false,
    flag: false,
    buttonType: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-TRUS-P-C-024",
    version: 1,
    garmentType: "TRUSA",
    garmentSubtype: null,
    designDetail:
      "TRUSAS - TRUSA CICLISMO / TRUSA PATINAJE / CAMISETA CICLISMO / LICRA DE CICLISMO",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-TRUS-GIM-NATACION-026",
    version: 1,
    garmentType: "TRUSA",
    garmentSubtype: "GIMNASIA - NATACION",
    designDetail: "TRUSAS GIMNASIA - NATACION",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-TRUS-BOD-027",
    version: 1,
    garmentType: "TRUSA",
    garmentSubtype: "PORRISMO",
    designDetail:
      "TRUSAS PORRISMO - TRUSA BODY + SHORT / TRUSA CONJUNTO PORRISMO",
    fabric: null,
    color: null,
    gender: "FEMENINO",
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-FALDS-025",
    version: 1,
    garmentType: "FALDA",
    garmentSubtype: "SHORT",
    designDetail: "FALDA SHORT",
    fabric: null,
    color: null,
    gender: "FEMENINO",
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-E-ENF-028",
    version: 1,
    garmentType: "CHALECO",
    garmentSubtype: null,
    designDetail:
      "CHALECOS - ENGUATADO / CON FORRO / SIN FORRO / CIERRE EN BOLSILLOS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    hasPocket: true,
    pocketZipperColor: null,
    liningType: null,
    liningColor: null,
    hasInnerLining: false,
    zipperLocation: "BOLSILLOS",
    zipperColor: null,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-PTA-BEI-029",
    version: 1,
    garmentType: "PANTALON",
    garmentSubtype: "BEISBOLERO",
    designDetail: "PANTALON BEISBOLERO",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
  {
    moldingCode: "D.N-EMF-GR-TP-031",
    version: 1,
    garmentType: "ESTETICA",
    garmentSubtype: "GORRO - TAPABOCAS",
    designDetail: "ESTETICA - ENFERMERIA: GORRO - TAPABOCAS",
    fabric: null,
    color: null,
    gender: null,
    process: null,
    estimatedLeadDays: null,
    screenPrint: false,
    embroidery: false,
    buttonhole: false,
    snap: false,
    tag: false,
    flag: false,
    neckType: null,
    sesgoType: null,
    sesgoColor: null,
    hiladillaColor: null,
    hasLateralMesh: false,
    lateralMeshColor: null,
    observations: null,
    isActive: true,
  },
];
